from __future__ import annotations

from osm_raster_topology.config import LayerSpec


def default_layers() -> list[LayerSpec]:
    return [
        LayerSpec(
            name="road_topology_super",
            geometry_kind="line",
            description="Oversampled road topology raster for preserving connectivity and avoiding false merges.",
            band_index=1,
            burn_strategy="supercover_line",
            topology_role="graph_edge",
            tags={"highway": ["*"]},
        ),
        LayerSpec(
            name="road_direction_bits_super",
            geometry_kind="line",
            description="Oversampled per-pixel direction bitmask used to disambiguate local road geometry.",
            band_index=2,
            burn_strategy="direction_mask",
            topology_role="graph_edge_direction",
            tags={"highway": ["*"]},
        ),
        LayerSpec(
            name="node_anchor_super",
            geometry_kind="point",
            description="Oversampled graph node anchors for endpoints and junctions.",
            band_index=3,
            burn_strategy="node_anchor",
            topology_role="graph_node",
            tags={"highway": ["traffic_signals", "crossing"]},
        ),
        LayerSpec(
            name="building_fill",
            geometry_kind="polygon",
            description="Binary building footprint raster.",
            band_index=4,
            burn_strategy="polygon_fill",
            topology_role="building_face",
            tags={"building": ["*"], "building:part": ["*"]},
        ),
        LayerSpec(
            name="building_boundary",
            geometry_kind="line",
            description="Building footprint boundaries rasterized from polygon edges.",
            band_index=5,
            burn_strategy="polygon_boundary",
            topology_role="building_edge",
            tags={"building": ["*"], "building:part": ["*"]},
        ),
        LayerSpec(
            name="sports_fill",
            geometry_kind="polygon",
            description="Sports grounds and sports facilities area fill.",
            band_index=6,
            burn_strategy="polygon_fill",
            topology_role="sports_face",
            tags={"leisure": ["pitch", "stadium", "sports_centre", "sports_hall", "swimming_pool", "track"], "sport": ["*"]},
        ),
        LayerSpec(
            name="sports_boundary",
            geometry_kind="line",
            description="Sports grounds boundaries rasterized from polygon edges.",
            band_index=7,
            burn_strategy="polygon_boundary",
            topology_role="sports_edge",
            tags={"leisure": ["pitch", "stadium", "sports_centre", "sports_hall", "swimming_pool", "track"], "sport": ["*"]},
        ),
        LayerSpec(
            name="highway_class",
            geometry_kind="line",
            description="Primary road class raster encoding highway categories.",
            band_index=8,
            burn_strategy="primary_semantic",
            topology_role="road_semantic",
            tags={"highway": ["*"]},
        ),
        LayerSpec(
            name="road_access",
            geometry_kind="line",
            description="Access permission raster for drivable lines.",
            band_index=9,
            burn_strategy="primary_semantic",
            topology_role="road_semantic",
            tags={"access": ["*"]},
        ),
        LayerSpec(
            name="road_lanes",
            geometry_kind="line",
            description="Lane count raster for roads when lane metadata exists.",
            band_index=10,
            burn_strategy="primary_semantic",
            topology_role="road_semantic",
            tags={"lanes": ["*"]},
        ),
        LayerSpec(
            name="road_maxspeed_kph",
            geometry_kind="line",
            description="Speed-limit raster parsed into km/h-like numeric values.",
            band_index=11,
            burn_strategy="primary_semantic",
            topology_role="road_semantic",
            tags={"maxspeed": ["*"]},
        ),
        LayerSpec(
            name="turn_restriction_via_mask",
            geometry_kind="point",
            description="Via-node mask for turn restrictions, with full details stored in the topology sidecar.",
            band_index=12,
            burn_strategy="restriction_node",
            topology_role="traffic_rule",
            tags={"restriction": ["*"]},
        ),
    ]
